steps:

- task: AzureResourceGroupDeployment@2

  displayName: 'Azure Deployment: IaC Lab1 ARM_Templates'

  inputs:

    azureSubscription: 'Microsoft Azure Internal Consumption(38799598-962d-47e5-beb0-e391ff1577a1)'

    resourceGroupName: ARM

    location: 'South Central US'

    csmFile: 'Lab1/ARM-Template_Incremental_Sample_Lab1.json'
